### ISSUE TITLE
libz-ng-sys 1.1.20 fails to link where 1.1.16 worked

### ISSUE THREAD

**Issue by konstin** [rust-lang/libz-sys#227]
After upgrading from libz-ng-sys 1.1.16 to 1.1.20, we're getting linker failures on windows both in CI and locally (full log: https://github.com/astral-sh/uv/actions/runs/11598373662/job/32295408945?pr=8703):

```
          liblibz_ng_sys-3eff2929ed972d5f.rlib(deflate_quick.obj) : error LNK2019: unresolved external symbol __imp_isgraph referenced in function deflate_quick
          liblibz_ng_sys-3eff2929ed972d5f.rlib(trees.obj) : error LNK2001: unresolved external symbol __imp_isgraph
          liblibz_ng_sys-3eff2929ed972d5f.rlib(zutil.obj) : error LNK2019: unresolved external symbol __imp__aligned_free referenced in function zng_zcfree
          liblibz_ng_sys-3eff2929ed972d5f.rlib(zutil.obj) : error LNK2019: unresolved external symbol __imp__aligned_malloc referenced in function zng_zcalloc
          C:\Users\Konsti\projects\uv\target\debug\deps\uv.exe : fatal error LNK1120: 3 unresolved externals
```

**Comment by Byron** [comment]
Closing in favor of #225 .
